apiVersion: 1

datasources:
  - name: gdev-testdata
    isDefault: false
    type: testdata

  - name: server-monitoring
    type: mysql
    url: ${DB_HOST}:${DB_PORT}
    user: ${DB_USER}
    jsonData:
      database: ${DB_NAME}
      maxOpenConns: 100
      maxIdleConns: 100
      MaxIdleConnsAuto: true
      connMaxLifetime: 14400
      timeInterval: 5m
      timezone: +00:00
    secureJsonData:
      password: ${DB_PASS}
