name: Build and Release Grafana Plugin

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    env:
      GRAFANA_SERVER: ${{ secrets.GRAFANA_SERVER }}
      GRAFANA_ACCESS_POLICY_TOKEN: ${{ secrets.GRAFANA_TOKEN }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build plugin
        run: npm run build

      - name: Sign plugin
        run: npx @grafana/sign-plugin --rootUrls ${GRAFANA_SERVER}

      - name: Package release files
        run: |
          mkdir release
          cp -r dist release/
          cp docker-compose.yml release/
          cp .env.example release/
          cp -r provisioning release/
          cp Home.json release/
          tar -czf grafana-plugin-release.tar.gz -C release .

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: grafana-plugin-release.tar.gz
          tag_name: grafana-plugin-release
          name: Grafana Plugin Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
