name: Build and Release Grafana Plugin

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    env:
      GRAFANA_SERVER: ${{ secrets.GRAFANA_SERVER }}
      GRAFANA_ACCESS_POLICY_TOKEN: ${{ secrets.GRAFANA_TOKEN }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build plugin
        run: npm run build

      - name: Update Home.json with dynamic server
        run: |
          sed -i "s|__GRAFANA_SERVER__|${GRAFANA_SERVER}|g" Home.json

      - name: Sign plugin
        run: npx @grafana/sign-plugin --rootUrls http://${GRAFANA_SERVER}:3000

      - name: Package release files
        run: |
          mkdir -p release/monitoring-plugin
          cp -r dist release/monitoring-plugin/dist
          cp -r provisioning release/monitoring-plugin/provisioning
          cp Home.json release/Home.json
          cp docker-compose.yaml release/
          cp .env.example release/
          tar -czf grafana-plugin-release.tar.gz -C release .

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: grafana-plugin-release.tar.gz
          tag_name: grafana-plugin-release
          name: Grafana Plugin Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
